services:
  tram_analytics:
    # run init process for proper signal forwarding
    init: true
    build:
      # build from the repository root
      context: ..
      dockerfile: ./docker/Dockerfile-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    image: mssrchapelier/belgrade-tram-analytics:0.3.2-gpu
    container_name: belgrade-tram-analytics
    environment:
      # Docker-specific; used by the demo asset downloader
      WITH_DEMO_ASSETS: true
    env_file:
      - ../docker.env
    ports:
      # map container ports to host ports, to access the servers on the host
      - "8081:8081" # pipeline server, API
      - "8091:8091" # dashboard
    volumes:
      # assets (video file, weights, configs) from which to run the service
      - tram-analytics-assets:/app/assets

volumes:
  tram-analytics-assets:
