FROM python:3.13-slim
LABEL authors="Kirill Karpenko" description="Tram analytics system"

# Set the working directory
WORKDIR /app

# Copy the list of dependencies
COPY requirements/base/reqs-base.txt requirements/base.txt
COPY requirements/base/reqs-ultralytics.txt requirements/ultralytics.txt

# Install dependencies
# Note: Utilising a cache for pip for faster rebuilds
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip && \
    pip install -r requirements/base.txt

# Ultralytics: using the default version of PyTorch for use in a GPU inference environment
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements/ultralytics.txt

# Copy the files needed
COPY ../common ./common
COPY ../tram_analytics ./tram_analytics
COPY ../paths.py ./paths.py
COPY ../vendor ./vendor

# Set the application's entry point
ENTRYPOINT ["python", "-m", "tram_analytics.v1.launcher_joint"]